"""Reports routes - retrieve postmortems and export as Markdown, JSON, or PDF."""

from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import PlainTextResponse, Response
from sqlalchemy.orm import Session

from ...db.models import IncidentRecord
from ...db.session import get_db
from ...db.store import list_audit_events
from ..routes.auth import get_current_user
from ..schemas import PaginationResponse, PostmortemResponse, ReportItemResponse, ReportListResponse

router = APIRouter()


@router.get("", response_model=ReportListResponse)
async def list_reports(
    page: int = 1,
    page_size: int = 50,
    user=Depends(get_current_user),
    db: Session = Depends(get_db),
):
    page_value = page if isinstance(page, int) else 1
    page_size_value = page_size if isinstance(page_size, int) else 50
    query = db.query(IncidentRecord).filter(IncidentRecord.outcome.isnot(None))
    total = query.count() if hasattr(query, "count") else len(query.all())
    rows = (
        query.order_by(IncidentRecord.created_at.desc())
        .offset(max(0, (page_value - 1) * page_size_value))
        .limit(max(1, min(page_size_value, 500)))
        .all()
    )
    reports = []
    for row in rows:
        snapshot = row.state_snapshot or {}
        postmortem = snapshot.get("postmortem")
        if postmortem:
            reports.append({**postmortem, "status": row.status})
    return ReportListResponse(
        reports=[ReportItemResponse(**report).model_dump() for report in reports],
        pagination=PaginationResponse(page=page_value, page_size=page_size_value, total=total),
    ).model_dump()


@router.get("/{incident_id}", response_model=PostmortemResponse)
async def get_report(
    incident_id: str,
    user=Depends(get_current_user),
    db: Session = Depends(get_db),
):
    row = db.get(IncidentRecord, incident_id)
    if not row:
        raise HTTPException(status_code=404, detail="Incident not found")
    postmortem = (row.state_snapshot or {}).get("postmortem")
    if not postmortem:
        raise HTTPException(
            status_code=404, detail="Postmortem not yet available for this incident"
        )
    return PostmortemResponse(**postmortem).model_dump()


@router.get("/{incident_id}/export")
async def export_report(
    incident_id: str,
    format: str = "markdown",
    user=Depends(get_current_user),
    db: Session = Depends(get_db),
):
    row = db.get(IncidentRecord, incident_id)
    if not row:
        raise HTTPException(status_code=404, detail="Incident not found")

    state = row.state_snapshot or {}
    pm = state.get("postmortem")
    if not pm:
        raise HTTPException(status_code=404, detail="Postmortem not yet available")

    if format == "json":
        return pm

    alert = state.get("alert")
    hyps = state.get("hypotheses", [])
    events = list_audit_events(db, incident_id)
    time_to_recovery = (
        f"{pm['time_to_recovery_seconds']:.1f}s" if pm.get("time_to_recovery_seconds") else "N/A"
    )

    md = f"""# Incident Postmortem - {pm["incident_id"]}

## Summary
| Field | Value |
|---|---|
| Incident ID | `{pm["incident_id"]}` |
| Service | {pm["service"]} |
| Severity | {alert["severity"] if alert else "N/A"} |
| Outcome | **{pm["outcome"]}** |
| Time to Recovery | {time_to_recovery} |
| Retry Count | {pm["retry_count"]} |
| Total LLM Cost | ${pm["total_cost_usd"]:.4f} |
| Created At | {pm["created_at"]} |

## Alert
{alert["description"] if alert else "No alert details"}

## Root Cause
{pm["root_cause_confirmed"]}

## Fix Applied
`{pm["fix_applied"]}`

## Hypotheses Considered
"""
    for index, hypothesis in enumerate(hyps):
        md += f"\n### Hypothesis {index + 1}: {hypothesis['description'][:100]}\n"
        md += f"- **Confidence:** {hypothesis['confidence']:.0%}\n"
        md += f"- **Attempted:** {hypothesis['attempted']}\n"
        md += f"- **Evidence:** {', '.join(hypothesis['evidence'][:3])}\n"

    md += "\n## Audit Trail\n"
    for event in events:
        md += f"- `{event['timestamp']}` {event['type']}\n"

    md += f"\n## Alert Signature\n`{pm['alert_signature']}`\n"
    md += "\n---\n*Generated by ASHIA - Agentic AIOps Self-Healing Infrastructure Agent*\n"

    if format == "markdown":
        return PlainTextResponse(content=md, media_type="text/markdown")

    if format == "pdf":
        try:
            from io import BytesIO

            from reportlab.lib.pagesizes import letter
            from reportlab.pdfgen import canvas

            buffer = BytesIO()
            pdf = canvas.Canvas(buffer, pagesize=letter)
            width, height = letter
            y = height - 50
            pdf.setTitle(f"ASHIA Postmortem {pm['incident_id']}")
            pdf.setFont("Helvetica-Bold", 14)
            pdf.drawString(50, y, f"ASHIA Incident Postmortem - {pm['incident_id']}")
            y -= 28
            pdf.setFont("Helvetica", 10)
            for line in md.splitlines():
                if y < 50:
                    pdf.showPage()
                    pdf.setFont("Helvetica", 10)
                    y = height - 50
                pdf.drawString(50, y, line[:110])
                y -= 14
            pdf.save()
            buffer.seek(0)
            return Response(content=buffer.read(), media_type="application/pdf")
        except Exception as exc:
            raise HTTPException(
                status_code=500,
                detail=f"PDF export unavailable in current runtime: {exc}",
            ) from exc

    raise HTTPException(status_code=400, detail="Unsupported export format")
